name: Building(CMake)

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:

  windows-build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows 2019 MSVC",
            artifact: "Windows-MSVC.tar.xz",
            os: windows-2019,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
      - uses: actions/checkout@v4

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ./build/Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          target:  desktop
          dir: '${{ github.workspace }}/build/'

      - name: Configure
        working-directory: build
        shell: powershell
        run: |
          cmake -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE ../

      - name: Build
        working-directory: build
        shell: powershell
        run: |
          cmake --build . --config $env:BUILD_TYPE
